import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import React, { ReactElement } from "react";

import { fetchPageFolders } from "src/api/fetchPageFolders";

import Layout from "src/components/Layout";
import Sidebar from "src/components/Sidebar";

import { PageFolder } from "types/pageFolderType";

interface Props {}

const FolderPage = ({}: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>ALLLLL</h1>
    </>
  );
};

FolderPage.getLayout = function getLayout(page: ReactElement) {
  return <Layout sidebarComponent={<Sidebar />}>{page}</Layout>;
};

export default FolderPage;

export const getServerSideProps: GetServerSideProps = async ({
  params,
  locale,
}) => {
  let pageFolders: PageFolder[] = [];

  try {
    pageFolders = await fetchPageFolders();
  } catch (e) {
    console.log(e);
  }

  const currentPageFolder = pageFolders.find(
    (pageFolder) => pageFolder.subDomain === params?.folder
  );

  return {
    notFound: !currentPageFolder,
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};
