import React from "react";
import { GetServerSideProps } from "next/types";
import Head from "next/head";

import Layout from "src/components/Layout";
import CardDetails from "src/components/CardDetails/CardDetails";

import { getPostCategories } from "helpers/changePostsData";
import Sidebar from "src/components/Sidebar";

type Props = {
  post: any;
};

const Post = ({ post }: Props) => {
  const categories = getPostCategories(post, "oldCategories");
  const companyImg = post?.companyId?.avatar || null;
  const title = post.title;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://ceditor.setka.io/clients/Xs9xVInUxQHyhtJghPIu3egpgew1OFU6/css/3705_ninonin_limited_1_1241.min.css"
          rel="stylesheet"
        />
        <script
          defer
          src="https://ceditor.setka.io/public/3.0.14/01/01/public.v3.0.14.1625249728.min.js?ver=2.1.10"
        ></script>
      </Head>

      <Layout SidebarComponent={Sidebar}>
        <CardDetails
          categories={categories}
          companyImg={companyImg}
          title={title}
        >
          <div dangerouslySetInnerHTML={{ __html: post.description }} />
        </CardDetails>
      </Layout>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const responsePost = await fetch(
    `https://api.jidipi.com/api/v1/post/public/${query.slug}/en`
  );

  const post = await responsePost.json();

  return {
    props: {
      post: post,
    },
  };
};

export default Post;
