import React, { ReactElement } from "react";
import Head from "next/head";
import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import Layout from "src/components/Layout";
import CompanyProfile from "src/components/CompanyProfile/CompanyProfile";

import { fetchCompanyInfo } from "src/api/fetchCompanyInfo";

import { CompanyInfo } from "types/companyInfoTypes";

interface Props {
  companyInfo: CompanyInfo;
}

const FolderPage = ({ companyInfo }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ width: "100%", backgroundColor: "#fff" }}>
        <div style={{ maxWidth: "900px", margin: "0 auto" }}>
          <CompanyProfile comnanyInfo={companyInfo} />
        </div>
      </div>
    </>
  );
};

FolderPage.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default FolderPage;

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  let companyInfo: CompanyInfo | {} = {};

  try {
    companyInfo = await fetchCompanyInfo("8e9-4m8");
  } catch (e) {
    console.log(e);
  }

  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
      companyInfo,
    },
  };
};
