import type { GetServerSideProps, NextPage } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";

import { useTranslation } from "next-i18next";

import SampleComponent from "src/components/SampleComponent";
import Navbar from "src/components/Navbar";
import Card from "src/components/Card";
import Layout from "src/components/Layout";

const Home: NextPage = () => {
  const { t } = useTranslation();

  const testData = [
    { title: "House in Laax" },
    { title: "House in Laax" },
    // { title: "House in Laax" },
    // { title: "House in Laax" },
    // { title: "House in Laax" },
    // { title: "House in Laax" },
    // { title: "House in Laax" },
    // { title: "House in Laax" },
    // { title: "House in Laax" },
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div
          style={{
            width: "100%",
            minHeight: "100%",
            padding: "20px 40px",
            backgroundColor: "rgb(0, 0, 0, 0.1)",
            display: "flex",
            flexWrap: "wrap",
          }}
        >
          {testData.map(({ title }, index) => (
            <div key={index} style={{ width: 350, margin: "0 20px 20px 0" }}>
              <Card title={title} />
            </div>
          ))}
        </div>
      </Layout>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale as string, ["common"])),
  },
});
