import type { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";

import { useTranslation } from "next-i18next";

import Card from "src/components/Card";
import Layout from "src/components/Layout";

import { changePostsData } from "helpers/changePostsData";

interface Props {
  posts: any;
  sidebarCategories: any;
}

const Home = ({ posts, sidebarCategories }: Props) => {
  const { t } = useTranslation();

  console.log(sidebarCategories);

  const data = changePostsData(posts.posts);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout sidebarCategories={sidebarCategories}>
        {data.map(({ title, categories, image, id }, index) => (
          <div key={index} style={{ width: 450, margin: "0 20px 20px 0" }}>
            <Card title={title} categories={categories} image={image} id={id} />
          </div>
        ))}
      </Layout>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  const responsePosts = await fetch(
    "https://api.jidipi.com/api/v1/post/public/603ce60958c5c6279bc2ed96?pageNumber=0&pageSize=100&language=EN"
  );

  const responseSidebarCategories = await fetch(
    "https://api.jidipi.com/api/v1/category?pageFolderId=603ce60958c5c6279bc2ed96"
  );

  const posts = await responsePosts.json();
  const sidebarCategories = await responseSidebarCategories.json();

  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
      posts: posts,
      sidebarCategories: sidebarCategories,
    },
  };
};
