import Head from "next/head";
import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import Layout from "src/components/Layout";

import UserPanelData from "src/components/UserPanelData/UserPanelData";
import PanelTable from "src/components/PanelTable/PanelTable";
import SidebarWithAvatar from "src/components/SidebarWithAvatar/SidebarWithAvatar";

import { fetchPageFolders } from "src/api/fetchPageFolders";

import { PageFolder } from "types/pageFolderType";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout SidebarComponent={<SidebarWithAvatar />} pageFolders={[]}>
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          <UserPanelData />
          <PanelTable />
        </div>
      </Layout>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  let pageFolders: PageFolder[] = [];

  try {
    pageFolders = await fetchPageFolders();
  } catch (e) {
    console.log(e);
  }

  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
      pageFolders,
    },
  };
};

export default Home;
